import type { Metadata } from "next";
import { Inter } from "next/font/google"

import { TRPCReactProvider } from "@/trpc/client";

import "./globals.css";
import { DashboardNavbar } from "@/modules/dashboard/ui/components/dashboard-navbar";

const inter = Inter({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Renders the root application layout.
 *
 * @param children - The page content to render inside the document body.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider>
      <html lang="en">
        <body
          className={`${inter.className} antialiased`}
        >
          {children}
        </body>
      </html>
    </TRPCReactProvider>
  );
}
